language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
before_install:
  - "pushd .."
  - "git clone https://github.com/pulp/pulp.git --branch 2.6-release"
  - "git clone https://github.com/pulp/nectar.git"
  - "pushd nectar"
  - "git checkout python-nectar-1.1.6-1"
  - "popd"
  - "popd"
install:
  # This is needed to build M2Crypto
  - "sudo apt-get install swig"
  - "pip install -r test_requirements.txt"
  # 2.5 didn't have its dependencies in its setup.py, so we need to install them too
  - "pip install okaara pymongo iniparse mongoengine"
  - "pushd .."
  - "python nectar/setup.py develop"
  - "pulp/manage_setup_pys.sh develop"
  - "popd"
  - "./manage_setup_pys.sh develop"
  - "sudo mkdir -p /etc/pulp"
  - "sudo touch /etc/pulp/server.conf"
script:
  - "./run-tests.py --enable-coverage"
after_success: coveralls
