# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: false
check_commit_message: true
check_manifest: true
check_stray_pulpcore_imports: true
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: true
plugin_app_label: python
plugin_camel: PulpPython
plugin_camel_short: Python
plugin_caps: PULP_PYTHON
plugin_caps_short: PYTHON
plugin_dash: pulp-python
plugin_dash_short: python
plugin_name: pulp_python
plugin_snake: pulp_python
publish_docs_to_pulpprojectdotorg: false
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: null
pydocstyle: true
pypi_username: pulp
redmine_project: null
stable_branch: null
test_bindings: false
test_cli: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: false
test_s3: false
travis_addtl_services: []
travis_notifications: None
update_redmine: false

